### ISSUE TITLE
Exception More than Int.MaxValue elements

### ISSUE THREAD

**Issue by YuelongCai** [spark-redshift-community/spark-redshift#147]
https://github.com/spark-redshift-community/spark-redshift/blob/20e7ccbb17b06be26dad9c5e894f92dee0845fa5/src/main/scala/io/github/spark_redshift_community/spark/redshift/RedshiftRelation.scala#L125

Caused by: java.lang.IllegalArgumentException: More than Int.MaxValue elements.
	at scala.collection.immutable.NumericRange$.check$1(NumericRange.scala:318)
	at scala.collection.immutable.NumericRange$.count(NumericRange.scala:328)
	at scala.collection.immutable.NumericRange.numRangeElements$lzycompute(NumericRange.scala:53)
	at scala.collection.immutable.NumericRange.numRangeElements(NumericRange.scala:52)
	at scala.collection.immutable.NumericRange.length(NumericRange.scala:55)
	at org.apache.spark.rdd.ParallelCollectionRDD$.slice(ParallelCollectionRDD.scala:143)

**Comment by YuelongCai** [comment]
The possible solution is 

if the total count is too big, like N
to split it into multiple rdds, each should be less than int.MaxValue and union all to generate rdd with size N

for example,
sc.parallelize(1L to 1000000000L, 200).union(sc.parallelize(1L to 1000000000L, 200)).union(sc.parallelize(1L to 1000000000L, 200)).union(sc.parallelize(1L to 1000000000L, 200)) will avoid this issue

**Comment by bsharifi** [comment]
Thank you @YuelongCai for reporting this limitation and suggestions on how to work around it. While we will consider addressing this in a future release, please feel free to submit a PR and we will be happy to review and merge it.
