### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.apache.spark.util.JsonProtocol

### ISSUE THREAD

**Issue by dbranscombe** [spark-redshift-community/spark-redshift#50]
Running on EMR 2.6  via Zeppelin (spark 2.4.3 and Zeppelin 0.8.1). 
Trying to run basic load:
```
val df = spark
      .read
      //.format("com.databricks.spark.redshift")
      .format("io.github.spark_redshift_community.spark.redshift")
      .option("url", redshiftUrl)
      .option("tempdir", redshiftTempDir)
      .option("dbtable", redshiftTableName)
      .option("aws_iam_role", redshiftIAMRole)
      .load
```

Getting 
```
ava.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.util.JsonProtocol$
	at org.apache.spark.scheduler.EventLoggingListener$.initEventLog(EventLoggingListener.scala:306)
	at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:125)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:523)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:936)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:927)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:927)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.zeppelin.spark.BaseSparkScalaInterpreter.spark2CreateContext(BaseSparkScalaInterpreter.scala:246)
	at org.apache.zeppelin.spark.BaseSparkScalaInterpreter.createSparkContext(BaseSparkScalaInterpreter.scala:178)
	at org.apache.zeppelin.spark.SparkScala211Interpreter.open(SparkScala211Interpreter.scala:89)
	at org.apache.zeppelin.spark.NewSparkInterpreter.open(NewSparkInterpreter.java:102)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:62)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:69)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:616)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:188)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucagiovagnoli** [comment]
Hi, thanks for opening this issue!

1. Unfortunately we recently dropped IAM support. Check the [CHANGELOG](https://github.com/spark-redshift-community/spark-redshift/blob/master/CHANGELOG#L10). I'd be very happy to support IAM again but I don't have the bandwidth to work on this. Feel free to push out a PR if you need it, I'll be happy to review it.
2. We don't do testing on EMR at the moment. Again, I'd be happy to review any PR to introduce an acceptance testing for EMR. From your exception I expect we'll need to figure out what jars are on EMR 2.6 first, because  I see you're getting a NoClassDefFoundError, so some are definitely missing.

**Comment by lucagiovagnoli** [comment]
Hi, thanks for opening this issue!

1. Unfortunately we recently dropped IAM support. Check the [CHANGELOG](https://github.com/spark-redshift-community/spark-redshift/blob/master/CHANGELOG#L10). I'd be very happy to support IAM again but I don't have the bandwidth to work on this. Feel free to push out a PR if you need it, I'll be happy to review it.
2. We don't do testing on EMR at the moment. Again, I'd be happy to review any PR to introduce an acceptance testing for EMR. From your exception I expect we'll need to figure out what jars are on EMR 2.6 first, because  I see you're getting a NoClassDefFoundError, so some are definitely missing.

**Comment by dbranscombe** [comment]
Thanks for the response and your work!

Re 1. Darn. IAM could be a deal breaker...off the top how invasive was your pull out of it? Any idea pain involved in getting it working?

**Comment by lucagiovagnoli** [comment]
We didn't really remove any code related to IAM, but I did remove IAM authentication tests, so I don't know if it works or not.

Creating a IAM test would be the first step, it should not be too much work. You can start by re-adding [this test](https://github.com/databricks/spark-redshift/blob/184b4428c1505dff7b4365963dc344197a92baa9/src/it/scala/com/databricks/spark/redshift/IAMIntegrationSuite.scala) in this repo and make it work.
