### ISSUE TITLE
java.io.StreamCorruptedException: invalid type code: 00 when the app is running on OpenShift in a client mode

### ISSUE THREAD

**Issue by ikarol** [spark-redshift-community/spark-redshift#98]
Hey,

I've been trying to figure this issue out for a while, but to no avail.

We have a spark job that uses spark-redshift(spark-redshift_2.12@master-SNAPSHOT).
When I run it in client mode via docker run (e.g. spark-submit  /opt/spark/work-dir/spark-transformations-0.1-jar-with-dependencies.jar) it works great. 
But as soon we run it on OpenShift via our image(that has a little bit different spark-submit call, see below), it breaks with this cryptic error:

```
Caused by: java.io.StreamCorruptedException: invalid type code: 00
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readBlockHeader(Unknown Source)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.refill(Unknown Source)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.read(Unknown Source)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readByte(Unknown Source)
        at java.base/java.io.ObjectInputStream.readByte(Unknown Source)
        at org.apache.hadoop.io.WritableUtils.readVLong(WritableUtils.java:308)
        at org.apache.hadoop.io.WritableUtils.readVInt(WritableUtils.java:329)
        at org.apache.hadoop.conf.Configuration.readFields(Configuration.java:3762)
        at io.github.spark_redshift_community.spark.redshift.SerializableConfiguration.$anonfun$readObject$1(SerializableConfiguration.scala:39)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at io.github.spark_redshift_community.spark.redshift.SerializableConfiguration.tryOrIOException(SerializableConfiguration.scala:44)
        at io.github.spark_redshift_community.spark.redshift.SerializableConfiguration.readObject(SerializableConfiguration.scala:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
        at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
        at org.apache.spark.broadcast.TorrentBroadcast$.$anonfun$unBlockifyObject$4(TorrentBroadcast.scala:336)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:338)
        at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$4(TorrentBroadcast.scala:257)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$2(TorrentBroadcast.scala:231)
        at org.apache.spark.util.KeyLock.withLock(KeyLock.scala:64)
        at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$1(TorrentBroadcast.scala:226)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1405)
        at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:226)
        at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:103)
        at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
        at io.github.spark_redshift_community.spark.redshift.RedshiftFileFormat.$anonfun$buildReader$1(RedshiftFileFormat.scala:81)
        at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:147)
        at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:132)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:116)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:169)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
Spark-submit command that we run as a part of the shell script in our image:
```
/opt/spark/bin/spark-submit \
  --master "$JOB_MASTER" \
  --driver-memory "$DRIVER_MEMORY" \
  --driver-cores "$DRIVER_CORES" \
  --executor-memory "$EXECUTOR_MEMORY" \
  --executor-cores "$EXECUTOR_CORES" \
  --deploy-mode "client" \
  --name "$POD_NAME" \
  --driver-class-path "$JOB_JAR" \
  --conf spark.sql.shuffle.partitions="$SHUFFLE_PARTITIONS" \
  --conf spark.executor.extraClassPath="$JOB_JAR" \
  --conf spark.kubernetes.namespace="$POD_NAMESPACE" \
  --conf spark.kubernetes.container.image="$JOB_IMAGE" \
  --conf spark.kubernetes.driver.request.cores="$DRIVER_REQUEST_CORES" \
  --conf spark.kubernetes.driver.limit.cores="$DRIVER_CORES" \
  --conf spark.kubernetes.executor.request.cores="$EXECUTOR_REQUEST_CORES" \
  --conf spark.kubernetes.executor.limit.cores="$EXECUTOR_CORES" \
  --conf spark.kubernetes.container.image.pullSecrets="$IMAGE_PULL_SECRETS" \
  --conf spark.kubernetes.container.image.pullPolicy="Always" \
  --conf spark.executor.instances="$EXECUTOR_INSTANCES" \
  --conf spark.driver.host="$POD_IP" \
  --conf spark.driver.port=14536 \
  --conf spark.kubernetes.executor.label.jobId="$JOB_ID" \
  --conf spark.kubernetes.executor.label.pipelineJobId="$PIPELINE_JOB_ID" \
  "$JOB_JAR" \
  -Dlog4j2.configurationFile=/opt/spark/conf/log4j.properties
```
The job has been built with the same version of Spark & Hadoop that we have installed in our image:
Spark - 3.1.1
Hadoop - 3.2.0

If the information that I've provided is not enough, please do let me know.
Thanks in advance!

**Comment by 88manpreet** [comment]
Can you try using Spark version: 3.0.2?
What is the difference b/w arguments of the two different spark-submit commands being used?
